=== ashokatano77/SUSHI/Examenparcial/academia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="academia">
    <xs:complexType>
        <xs:sequence>

        <xs:element name="clase" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>

                <xs:element name ="estilo" type="xs:string"/>
                <xs:element name ="precio" type="xs:string"/>
                <xs:element name ="plazas" type="xs:string"/>
                <xs:element name ="inicio" type="xs:string"/>
                <xs:element name ="fin" type="xs:string"/>
                <xs:element name ="dias" type="xs:string"/>
                <xs:element name ="profe" type="xs:string"/>
                <xs:element name ="sala" type="xs:string"/>

                </xs:sequence>
            </xs:complexType>
        </xs:element>

        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== ashokatano77/SUSHI/Examen2ºav/academia.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="academia.xsl" type="text/xsl"?>
<academia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="academia.xsd">
    <clase>
        <estilo>Bachata</estilo>
        <precio>60 €</precio>
        <plazas>12</plazas>
        <inicio>1.1.2023</inicio>
        <fin>31.12.2023</fin>
        <dias>Lunes, Miercoles</dias>
        <profe>Fiona</profe>
        <sala>1</sala>
    </clase>

    <clase>
        <estilo>Tango</estilo>
        <precio>70 €</precio>
        <plazas>16</plazas>
        <inicio>1.1.2023</inicio>
        <fin>1.6.2023</fin>
        <dias>Viernes</dias>
        <profe>Sofia</profe>
        <sala>2</sala>
    </clase>


    <clase>
        <estilo>Twerk</estilo>
        <precio>50 €</precio>
        <plazas>25</plazas>
        <inicio>1.1.2023</inicio>
        <fin>1.9.2023</fin>
        <dias>Martes, Jueves</dias>
        <profe>Bruno </profe>
        <sala>3</sala>
    </clase>


    <clase>
        <estilo>Bals</estilo>
        <precio>65 €</precio>
        <plazas>18</plazas>
        <inicio>1.1.2023</inicio>
        <fin>1.4.2023</fin>
        <dias>Miercoles</dias>
        <profe>Bruno </profe>
        <sala>1</sala>
    </clase>

    <clase>
        <estilo>Sevillanas</estilo>
        <precio>34 €</precio>
        <plazas>20</plazas>
        <inicio>1.1.2023</inicio>
        <fin>31.12.2023</fin>
        <dias>Lunes, Miercoles</dias>
        <profe>Sofia </profe>
        <sala>2</sala>
    </clase>

    <clase>
        <estilo>Salsa</estilo>
        <precio>55 €</precio>
        <plazas>26</plazas>
        <inicio>1.1.2023</inicio>
        <fin>1.7.2023</fin>
        <dias>Martes, Jueves</dias>
        <profe>Fiona </profe>
        <sala>3</sala>
    </clase>


    
</academia>
