=== ashokatano77/SUSHI/act23/act23.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="FACTURA">
    <xs:complexType>
        <xs:sequence>

        <xs:element name="FACTURA">
            <xs:complexType>
                <xs:sequence>

                <xs:element name="proveedor" maxOccurs="unbounded"> 
                    <xs:complexType>
                        <xs:sequence>

                        <xs:element name="empresa" type="xs:string"/>
                        <xs:element name="calle" type="xs:string"/>
                        <xs:element name="provincia" type="xs:string"/>
                        <xs:element name="cif" type="xs:string"/>
                        <xs:element name="telefono" type="xs:string"/>
                        <xs:element name="fax" type="xs:string"/>
                        
                       </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="registro"  minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="fecha" type="xs:string"/>
                            <xs:element name="pedido" type="xs:string"/>
                            <xs:element name="formadepago" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="datoscliente">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="numero" type="xs:string"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="poblacion" type="xs:string"/>
                            <xs:element name="codigopostal" type="xs:string"/>
                            <xs:element name="provincia" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="datosfactura">
                    <xs:complexType>
                        <xs:sequence>

                        <xs:element name="dato" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>

                                    <xs:element name="ref" type="xs:string"/>
                                    <xs:element name="descripcion" type="xs:string"/>
                                    <xs:element name="cantidad" type="xs:string"/>
                                    <xs:element name="precio" type="xs:string"/>
                                    <xs:element name="iva" type="xs:string"/>
                                    <xs:element name="importe" type="xs:string"/>


                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="totaldatos">
                            <xs:complexType>
                                <xs:sequence>

                                <xs:element name="baseimponible" type="xs:string"/>

                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="totalfactura">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="cantidad" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                           

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>



                </xs:sequence>
            </xs:complexType>
        </xs:element>

        </xs:sequence>
    </xs:complexType>
</xs:element>


</xs:schema>

=== ashokatano77/SUSHI/act23/act23.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="act23.xsl" type="text/xsl"?>
<FACTURA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="act23.xsd">

    


    <proveedor>
        <empresa>Equipos Digitales S.L</empresa>
        <calle>Av.Valladolid</calle>
        <provincia>Madrid 28015</provincia>
        <cif>C.I.F: Q-9876543</cif>
        <telefono>teléfono: 91.777.66.99</telefono>
        <fax>fax: 91.777.66.99</fax>
    </proveedor>


    <registro>
        <fecha>Fecha: 12-01-2005</fecha>
        <pedido>Pedido: nº 731</pedido>
        <formadepago>Forma de pago: EFECTIVO</formadepago>
    </registro>
    

    <datoscliente>
        <numero>nº cliente: 879</numero>
        <nombre>Nombre: Dario Bueno Gutiérrez</nombre>
        <direccion>Dierección de envio: Av. Oporto nº7 4ºd</direccion>
        <poblacion>Población: Madrid</poblacion>
        <codigopostal>Cod. postal: 28043</codigopostal>
        <provincia>Provincia: Madrid</provincia>
    </datoscliente>


    <datosfactura>
        
        <dato>
            <ref>MII93000F/8 </ref>
            <descripcion>MICRO PENTIUM IV 3000MHZ FB3800</descripcion>
            <cantidad>1</cantidad>
            <precio>230 eur.</precio>
            <iva>16,0</iva>
            <importe>266,80 eur.</importe>
        </dato>
        
        <dato>
             <ref>MBBQDIP4</ref>
             <descripcion>PLACA BASE QDI P4</descripcion>
             <cantidad>1</cantidad>
             <precio>180 eur.</precio>
             <iva>16,0</iva>
             <importe>208,80 eur.</importe>
        </dato>
        
        <dato>
            <ref>MEDD512M32</ref>
            <descripcion>DIMM DDR 512MB 3200</descripcion>
            <cantidad>2</cantidad>
            <precio>40 eur.</precio>
            <iva>16,0</iva>
            <importe>92,80 eur.</importe>
        </dato>
        
        <dato>
            <ref>HD250GSA7</ref>
            <descripcion>DISCO DURO 250GB S-ATA 7200</descripcion>
            <cantidad>4</cantidad>
            <precio>120 eur.</precio>
            <iva>16,0</iva>
            <importe>556,80 eur.</importe>
        </dato>
        
        <totaldatos>
            <baseimponible>970,00 eur.</baseimponible>
            <iva>16</iva>
            <cuotaiva>155,20 eur.</cuotaiva>
        </totaldatos>
        
        <totalfactura>
            <cantidad>TOTAL FACTURA:   1125,20 eur.</cantidad>
         </totalfactura>
        
    </datosfactura>



</FACTURA>
